project:
  type: website
  resources: assets/

website:
  title: "Robot Modeling Control"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
    right: 
      - href: https://uk.instructure.com/courses/2151702
        text: Canvas
  sidebar:
      style: "docked"
      search: true
      contents:
        - text: "Python"
          href: introduction.qmd
        - schedule.qmd
        - papers.qmd
        - extras.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



