project:
  type: website
  resources: assets/

website:
  title: "Robot Modeling Control"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - schedule.qmd
      - about.qmd
    right: 
      - href: https://uk.instructure.com/courses/2151702
        text: Canvas
  sidebar:
      style: "docked"
      search: true
      contents:
        - text: "Python"
          href: introduction.qmd
        - schedule.qmd
        - papers.qmd
        - extras.qmd
        - text: "Matrix Review (LQR)"
          href: matrix_review.qmd
        - text: "Block Systems & Schur Complement"
          href: schur_complement.qmd
        - text: "LQR"
          href: lqr_opt_activity.qmd
        - text: "Polynomial Trajectory Blending"
          href: poly_blend.qmd
        - text: "Simple Pendulum (phase portrait)"
          href: pendulum.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



