---
title: "Python Setup"
format: 
  html:
    standalone: false
    self-contained: false

execute: 
  echo: false
  freeze: auto
---

## Windows 

See [this guide](https://docs.python.org/3/using/windows.html) or [this guide](https://www.digitalocean.com/community/tutorials/install-python-windows-10) to using `python` on Windows. 

## Command Line Tools 

See this [short course](https://missing.csail.mit.edu/) for using the command line to run things on your computer. 

## Packages

We use the following major packages in `python`: 

1. `numpy`: working with $n$-D arrays 
1. `mujoco` : Modeling and simulation of robotic systems
1. `matplotlib`: plotting

The following command uses `pip` to install these `python` packages 
```
pip install numpy mujoco matplotlib
```
If you want to use machine learning, consider the following packages:

1. `torch`: training of differentiable models 
1. `torchvision`: tools for vision models
1. `pandas`: working with data 
1. `tqdm`: progress bars in the command line 
1. `scikit-learn`: source some classic datasets



### Virtual Environment 

Virtual environments allow you to install a custom set of packages with custom package versions for a project. 

Inside the `robotics-course` directory, run
```
python -m venv code-venv
```
to create a blank virtual environment. 

Activate it, and then install packages. Upon activation, the command line prompt changes to start with the name of the virtual environment. Here, it would be `(code-venv)`:
```
source code-venv/bin/activate
pip install <packages above>
```

When you are done, you can run `deactivate` to return to the default global environment. 

## NumPy

A nice overview of using `numpy` is located [online here](https://numpy.org/doc/stable/user/absolute_beginners.html). 

Two **KEY** issues to watch out for: 

1. Standard matrix multiplication in `numpy` uses the `@` symbol, not the `*` symbol. Users coming from `Matlab` or `Julia` often trip over this issue a few times until they internalize the new symbol. 
1. 2D Arrays are stored in row-major form. 


## MuJoCo


### Usage Example: Simulation

Once you have installed `mujoco` in `python`, put the code below in a file and then run this command from the command line:

```
python3 <filename where you placed code below>
```

If you use macOS, the use of `mujoco.viewer` for visualization requires a different command:

```
mjpython <filename where you placed code below>
```

```python
import mujoco
import mujoco.viewer
import time 

# Load a model from a file (won't do this here to avoid external file calls)
# model = mujoco.MjModel.from_xml_path('path/to/your/model.xml')

# Create a simple pendulum model from a string containing that xml
model = mujoco.MjModel.from_xml_string("""
<mujoco>
  <asset>
    <texture name="skybox" type="skybox" builtin="gradient" rgb1=".3 .5 .7" rgb2="0 0 0" width="100" height="100"/>
  </asset>
  
  <worldbody>
    <light name="light1" pos="0.3 0.3 1"/>
    <geom name="ground" type="plane" size="1 1 0.1" rgba="0.8 0.8 0.8 1"/>
    
    <body name="pendulum" pos="0 0 0">
      <joint name="pivot" type="hinge" pos="0 0 0" axis="0 1 0" damping="0.1"/>
      <geom name="rod" type="capsule" fromto="0 0 0 0 0 1" size="0.05" rgba="0.5 0.5 0.5 1"/>
      <geom name="mass" type="sphere" pos="0 0 1" size="0.1" rgba="0.8 0.2 0.2 1"/>
    </body>
  </worldbody>
</mujoco>
""")

## Set the time step, initial condition
dt: float = 0.002
model.opt.timestep = dt
data = mujoco.MjData(model)
data.qpos[0]=0.01

# Create a viewer
viewer = mujoco.viewer.launch_passive(model, data)
# Run a viewer with simulation in 'real-time'
try: 
    while viewer.is_running():
        step_start = time.time()
        # Step the simulation
        mujoco.mj_step(model, data)
        # Update the viewer
        viewer.sync()
        # Add a small delay to control frame rate
        time_until_next_step = dt - (time.time() - step_start)
        if time_until_next_step > 0:
            time.sleep(time_until_next_step)
except KeyboardInterrupt:
    print("Viewer closed by user")
finally:
    viewer.close()
```
