---
title: "Papers"
format: 
  html:
    standalone: false
    self-contained: false

execute: 
  echo: false
  freeze: auto

---

| Description           | Title                                                                                      | Source     | Preprint                                                                 |
|-----------------------|--------------------------------------------------------------------------------------------|------------|--------------------------------------------------------------------------|
| PID Control           | On the PID tracking control of robot manipulators                                          | [SCL](https://www.sciencedirect.com/science/article/pii/S0167691100000773?casa_token=jdLXKUgsuuUAAAAA:kvw-qjJcoIVUdbHKMUhTe23YRiR0thW6xvT9dfOLn79WQ1I5WcJ6fIc1iNWi-v8apaJ7YmQrdfI) |                                                                          |
| Gravity Compensation  | Gravity compensation in robotics                                                           | [T&F](https://www.tandfonline.com/doi/abs/10.1080/01691864.2015.1090334)      |                                                                          |
| Control               | Experimental evaluation of feedforward and computed torque control                         | [IEEE](https://ieeexplore.ieee.org/abstract/document/1088020)                |                                                                          |
| Force Control         | Compliance and Force Control for Computer Controlled Manipulators                          | [IEEE](https://ieeexplore.ieee.org/abstract/document/538974)                  |                                                                          |
| PDW                   | Passive Dynamic Walking                                                                    | [link](https://users.dimi.uniud.it/~antonio.dangelo/Robotica/2019/helper/leggedRobot/McGeer-Passive_dynamic_walking.pdf) |                                                                          |
| Hybrid Zero Dynamics  | Hybrid zero dynamics of planar biped walkers                                               | [IEEE](https://ieeexplore.ieee.org/abstract/document/1166523)                 |                                                                          |
| Underactuation        | The swing up control problem for the Acrobot                                                | [IEEE](https://ieeexplore.ieee.org/abstract/document/341864)                  |                                                                          |
| Underactuation        | Partial feedback linearization of underactuated mechanical systems                         | [IEEE](https://ieeexplore.ieee.org/document/407375)                           |                                                                          |
| Push recovery         | Capture Point: A Step toward Humanoid Push Recovery                                        | [IEEE](https://ieeexplore.ieee.org/abstract/document/4115602)                 |                                                                          |
| Quadrotor Diff Flatness | A prototype of an autonomous controller for a quadrotor UAV                              | [IEEE](https://ieeexplore.ieee.org/abstract/document/7068316)                 |                                                                          |
| Quadrotor             | Trajectory generation and control for precise aggressive maneuvers with quadrotors         | [IJRR](https://journals.sagepub.com/doi/abs/10.1177/0278364911434236)         |                                                                          |
| Differential Drive Robots | Minimum Wheel-Rotation Paths for Differential-Drive Mobile Robots                        | [IJRR](https://journals.sagepub.com/doi/abs/10.1177/0278364908096750)        |                                                                          |
| Medical               | Nonholonomic Modeling of Needle Steering                                                   | [IJRR](https://doi.org/10.1177%2F0278364906065388)                            |                                                                          |
| Consensus-based Methods | Consensus and Cooperation in Networked Multi-Agent Systems                               | [IEEE](https://ieeexplore.ieee.org/document/4118472)                          |                                                                          |
| Formation Control     | Modeling and control of formations of nonholonomic mobile robots                           | [IEEE](https://ieeexplore.ieee.org/abstract/document/976023)                  |                                                                          |
| Subsumption (Brooks)  | A robust layered control system for a mobile robot                                         | [IEEE](https://ieeexplore.ieee.org/abstract/document/1087032)                 |                                                                          |
| Exoskeletons          | Biomechanical design of the Berkeley lower extremity exoskeleton (BLEEX)                  | [IEEE](https://ieeexplore.ieee.org/abstract/document/1618670)                 |                                                                          |
| Filtering Body Pose   | Design, Implementation, and Experimental Results of a Quaternion-Based Kalman Filter for Human Body Motion Tracking | [IEEE](https://ieeexplore.ieee.org/abstract/document/4020379)                |                                                                          |
| Snake Robot           | Design of a modular snake robot                                                            | [IEEE](https://ieeexplore.ieee.org/abstract/document/4399617)                 |        
