---
title: "Topics"
format: 
  html:
    standalone: false
    self-contained: false

execute: 
  echo: false
  freeze: auto

coursepdf: assets/extras/
---

|Date		|Topic										| Slides						| [Notes](https://poonawalalab.github.io/rmc-s21/assets/pdf/00_RMC_Notes.pdf) | Modern Robotics Chapter[^2]	| RMC Book[^1]	|
|:---		|:---										|:---							|:---	|:---:						|:---:		|
|Jan 13	    | Course Overview; Motion Tasks				| [Overview](overview.html)		|								| 1	|1			|
|Jan 15	    | `MuJoCo` Setup							|[`MuJoCo`](mujoco.html)		| [webpage](introduction.html)	|  	| 			|
|Jan 20	    | Nonlinear Least squares					|[slides](nonlin_lsq.html)      |                             	|  	| 			|
|Jan 22	    | Scan Matching 							|[scan match](scanmatch.html), [NDT](ndt.html)|                             	|     	| 	    	|
|-     	    | Frames and Coordinates | [Euclidean Space](https://poonawalalab.github.io/rmc-s21/assets/pdf/04_Euclidean_Space.pdf)|  Ch 1                       	| 3.1 	| 	2.1		|
|Jan 27	    | Odometry      							|[odometry](lio.html)           |                        	|            	|           |
| -    	    | Homogenous Coordinates					|  [Homogenous Transformations](https://poonawalalab.github.io/rmc-s21/assets/pdf/05_Cartesian_Coordinates_Homogenous_Transformations.pdf)           |      Ch 1.5            	|   3.3.1    	| 	2.2-2.6		|
|Jan 29	    | Pose Graph Optimization					|[pose graph](posegraph.html)													|   	|  	| 			|
| -    	    | Extended Kalman Filter SLAM				| [EKF Slam](https://poonawalalab.github.io/rmc-s21/assets/pdf/25_SLAM.pdf)     |   	|  	| 			|
|Feb 03	    | Map Representations           			| 													| OneNote |  	| 			|				
|Feb 05	    | Motion Planning Overview				|[Overview](https://poonawalalab.github.io/rmc-s21/assets/pdf/21_Motion_Planning_0.pdf), [Search](https://poonawalalab.github.io/rmc-s21/assets/pdf/20_Search.pdf)													|  OneNote 	|  10.3	|5		|
|Feb 10	    | Search-based Motion Planning				|[Search](https://poonawalalab.github.io/rmc-s21/assets/pdf/20_Search.pdf)	|  OneNote 	| 10.3 	| 			|
|Feb 12	    | Motion Planning RRT, Polynomial Blends   	|[MP1](https://poonawalalab.github.io/rmc-s21/assets/pdf/21_Motion_Planning_I.pdf), [MP2](https://poonawalalab.github.io/rmc-s21/assets/pdf/22_Motion_Planning_II.pdf)													|   OneNote	| 10.3 	| 	5		|	
|Feb 17	    | Optimal Control   	|[Optimal Control PDF](https://poonawalalab.github.io/rmc-s21/assets/pdf/18_LQR.pdf)|   	| 	| 	|
| - |Linear Dynamical Systems| [Linearization]({{< meta coursepdf >}}/ME340_08_Linearization_Notes.pdf), [LTI Systems]({{< meta coursepdf >}}/ME340_10_Linear_State_Variable_Equations_Notes.pdf)|
|Feb 19	    | LQR   	|[OC Web slides](lqr.html), [Simple LQR](lqr_simple.html)| [Matrix Review](matrix_review.html)	| 	| 	|
|Feb 24	    | iLQR   	| [iLQR](ilqr.html) | 	| 	| 	|
|Feb 26	    | iLQR: Line Search, Forward Pass, MPC  	| [iLQR](ilqr.html), [MPC](mpc.html) | 	| 	| 	|
| - |ODEs| [ODE Slides]({{< meta coursepdf >}}/ME340_A1_Differential_Equations_Slides.pdf) [ODE Models]({{< meta coursepdf >}}/ME340_02_ODE_Models_Notes.pdf), [Mechanical Sys]({{< meta coursepdf >}}/ME340_03_Mechanical_Systems.pdf),  [Electrical Sys]({{< meta coursepdf >}}/ME340_04_Electrical\ Systems.pdf),
|Mar 03	    | Modeling   	| [Powered Mechanisms](assets/pdfs/02_Robots_As_Powered_Mechanisms.pdf) | Ch 3, OneNote	| Ch 3.1	| Ch 7.6	|
|Mar 05	    | Dynamics   	| [Dynamics](assets/pdfs/08_Euler_Lagrangian_Models.pdf), [Actuation](assets/pdfs/09_Actuation.pdf) | Ch 3, OneNote	| Ch 3.1	| Ch 7.6	|
| - |Control Systems|[Laplace Transforms]({{< meta coursepdf >}}/ME340_05_Laplace_Transform_Notes.pdf), [Transfer Functions]({{< meta coursepdf >}}/ME340_06_Transfer_Functions_Notes.pdf), [Stability]({{< meta coursepdf >}}/stability.pdf), [Feedback/forward Control](https://poonawalalab.github.io/rmc-s21/assets/pdf/10_Feedforward_Feedback_Tracking.pdf)  |
| Mar 10 | Independent Joint Control, Gravity Compensated PD| [IJC](https://poonawalalab.github.io/rmc-s21/assets/pdf/11_IJC_PID.pdf), [GravComp](https://poonawalalab.github.io/rmc-s21/assets/pdf/12_GC_PD.pdf) |4.1-4.2|11.4.2.1 | 6, 8.1|
| Mar 12 | Inverse Dynamics Control| [InvDyn](https://poonawalalab.github.io/rmc-s21/assets/pdf/13_Inverse_Dynamics_CTC.pdf)|4.2|11.4.2.2 | 8.2|
| Mar 24 | Forward Kinematics | [Fwd Kin](https://poonawalalab.github.io/rmc-s21/assets/pdf/06_Forward_Kinematics_Jacobians.pdf)|2.2;2.3|4 | 3.1|
| Mar 26 | Velocity Kinematics; Inverse Kinematics | [Vel Kin](assets/pdfs/05_Velocities_Of_Frames.pdf), [Inv Kin](assets/pdfs/07_Inverse_Kinematics.pdf)|2.2;2.3|3.3;6 | 4.1-4.5; 3.2|
| Mar 31 | Task Space Inv Dyn | [InvDyn](https://poonawalalab.github.io/rmc-s21/assets/pdf/13_Inverse_Dynamics_CTC.pdf)|4.2.3|11.4.2 | 9.3|
| Apr 2 | Project Proposal | || | |
| Apr 7 | Force and Impedance Control | | 4.4; 4.5| 11.5; 11.7 |9|


[^2]: [Modern Robotics wiki](https://hades.mech.northwestern.edu/index.php/Modern_Robotics#Book)

[^1]: _Robot Modeling and Control_, M. W. Spong, S. Hutchinson, and M. Vidyasagar, John Wiley \& Sons, 2006.
<!--
|Jan 17	    |Robots as powered mechanisms				|  \pdflink{Powered Mechanisms}{02_Robots_As_Powered_Mechanisms} | | 2.1-2.3|1|
| (self)	|Affine Spaces								| \pdflink{Euclidean Space}{04_Euclidean_Space}|\coursenotes{1}|
|Jan 19		|Reference Frames & Coordinates; Coordinate/Rigid Body Transformations| \pdflink{Euclidean Space}{04_Euclidean_Space}|\coursenotes{1}| 3.1|2.1|
|Jan 24		|Coordinate/Frame Transformation; Homogenous Transformations| \pdflink{Homogenous Transformations}{05_Cartesian_Coordinates_Homogenous_Transformations} |\coursenotes{ 1.5 } |3.3.1|2.2-2.6|
| (self)	|Forward Kinematics|  \pdflink{FwdKin}{06_Forward_Kinematics_Jacobians}| \coursenotes{2.2, 2.3} |4| 3.1|
|Jan 26		|Rotations| \pdflink{Rotations}{05_Rotation_Matrices} |\coursenotes{ 1.5 } |3.3.1|2.2-2.6|
| Jan 26	| Jacobians | \pdflink{Velocities}{05_Velocities_Of_Frames}| \coursenotes{2.2, 2.3} |5.1 | 4.6 |
| Jan 26 	| Twists, Wrenches|  \pdflink{TwistWrench}{05_Wrenches_and_Twists}|  |3.3|- |
| (self) 	|Inverse Kinematics|\pdflink{InvKin}{07_Inverse_Kinematics} |\coursenotes{2.2} | 6 | 3.2|
| (self) 	| Velocity Kinematics | \pdflink{Velocities}{05_Velocities_Of_Frames}| \coursenotes{2.2, 2.3} |3.3 | 4.1-4.5 |
|			| 2D Newton-Euler Dynamics| | \coursenotes{3.1} |3.1 | 7.6
|			| 3D Newton-Euler Dynamics| | \coursenotes{3.1} | 8.2| 7.6
|			|Euler-Lagrangian Dynamics| \pdflink{Dynamics}{08_Euler_Lagrangian_Models}| \coursenotes{3.2, 3.3} | 8.1, 8.4-8.5|7.1-7.4
|			|Newton-Euler Inverse Dynamics| | |8.3 |7.6 |
|			|Actuator Models|  \pdflink{Actuation}{09_Actuation}|\coursenotes{3} | 8.9| 6.5|
|			|Feedforward and Feedback Control|  [FF and FB](\fillnote/10_Feedforward_Feedback_Tracking.pdf)|\coursenotes{4.1}|  |
|			| Independent Joint Control| [IJC](\fillnote/11_IJC_PID.pdf)|\coursenotes{4.1}|11.4.2.1 | 6|
|			| Gravity Compensation | \pdflink{GravComp}{12_GC_PD}| \coursenotes{4.2} | | 8.1
|			| Inverse Dynamics Control| [InvDyn](\fillnote/13_Inverse_Dynamics_CTC.pdf)|\coursenotes{4.2}|11.4.2.2 | 8.2|
|			(self)|  Properties of EL Dynamics| \pdflink{Dynamics}{08_Euler_Lagrangian_Models}|\coursenotes{3.4} | 8.1|7.5|
|			| Robust and Adaptive Control| |\coursenotes{4.2.4,4.2.5}| | 8.3|
|			|Passivity-Based Control| |\coursenotes{4.3} | |8.4|
|			|Force Control| |\coursenotes{4.4} |11.5 |9|
|			|Contacts| |\coursenotes{4.4} |11.6 | 9.1|
|			|Hybrid Force-Position Control| |\coursenotes{4.4} |11.6 | 9.3.3|
|			|Impedance||\coursenotes{4.5} |11.7| 9.2|
|			|Hybrid Impedance Control||\coursenotes{4.5} |11.7| 9.3.2|
|			|Impedance Control||\coursenotes{4.5} |11.7| 9.3.2|
|			| Motion Planning |[MP0](\fillnote/21_Motion_Planning_0.pdf), [Search](\fillnote/20_Search.pdf), [MP1](\fillnote/21_Motion_Planning_I.pdf) |\coursenotes{5.1, 5.3, 5.4} |10.3| 5.2, 5.3 |
|			| Potential-based Methods|[MP2](\fillnote/22_Motion_Planning_II.pdf)|\coursenotes{5.2}|10.5| 5.4|
|			| Kalman Filtering|[Probability](\fillnote/23_Probability.pdf), [KF](\fillnote/24_State_Estimation.pdf)| | | |
|			| KF, SLAM|[SLAM](\fillnote/25_SLAM.pdf)| | | |
|			| SLAM, Review|[SLAM](\fillnote/25_SLAM.pdf)| | | |
|			| Brief: Optimal Control, RL|[LQR](\fillnote/18_LQR.pdf)| | | |
|			| | | | ||
|			|Feedback Linearization| | | |10.2|
|			|Grasping and Manipulation| | |- |
|			|Wheeled Mobile Robots| | | 13 |10.5 |
-->

